# Jekyll setup
#url: https://kmubiin.github.io
#baseurl: /fen
#permalink: /:title:output_ext
#plugins:
#  - jekyll-relative-links  # convert links .md to .html
theme:  # empty theme, otherwise random pick on GH
defaults:
  -
    scope:
      path: ""
    values:
      layout: "manual"
# apply the "default" or custom layout to all pages,
# otherwise front matter layout: is required in each file
